# Generated by Django 2.2.2 on 2019-06-13 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_hour', models.CharField(choices=[('0', 'H'), ('1', '1 hour'), ('2', '2 hours'), ('3', '3 hours'), ('4', '4 hours'), ('5', '5 hours'), ('6', '6 hours'), ('7', '7 hours'), ('8', '8 hours'), ('9', '9 hours'), ('10', '10 hours'), ('11', '11 hours'), ('12', '12 hours')], default=9, max_length=20)),
                ('start_time_min', models.CharField(choices=[('0', 'M'), ('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes')], default=0, max_length=20)),
                ('day_date', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=100)),
                ('days_num', models.IntegerField(default=1)),
                ('start_day', models.DateField(default='2002-02-22')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=' ')),
                ('duration_hour', models.CharField(choices=[('0', 'H'), ('1', '1 hour'), ('2', '2 hours'), ('3', '3 hours'), ('4', '4 hours'), ('5', '5 hours'), ('6', '6 hours'), ('7', '7 hours'), ('8', '8 hours'), ('9', '9 hours'), ('10', '10 hours'), ('11', '11 hours'), ('12', '12 hours')], default=0, max_length=20)),
                ('duration_min', models.CharField(choices=[('0', 'M'), ('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes')], default=0, max_length=20)),
                ('route_time', models.TextField(blank=True, null=True)),
                ('time_arr', models.TextField(blank=True, null=True)),
                ('time_leave', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trversalapp.Day')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='day',
            name='trip_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trversalapp.Trip'),
        ),
    ]
