# Generated by Django 2.2.1 on 2019-06-07 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='9:00 AM')),
                ('day_date', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=100)),
                ('days_num', models.IntegerField(default=1)),
                ('start_day', models.DateField(default='2002-02-22')),
                ('start_location', models.TextField(default='Portland, OR')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=' ')),
                ('duration_hour', models.IntegerField(default=1)),
                ('duration_min', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trversalapp.Day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='trip_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trversalapp.Trip'),
        ),
    ]
