# Generated by Django 2.2.1 on 2019-06-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trversalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
