# Generated by Django 2.2.1 on 2019-06-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trversalapp', '0002_location_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='location',
            name='route_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
