# Generated by Django 2.2.2 on 2019-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trversalapp', '0002_auto_20190621_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='g_name',
            field=models.TextField(default=' ', max_length=250),
        ),
    ]
