# Generated by Django 2.2.1 on 2019-06-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trversalapp', '0003_auto_20190610_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='start_location',
        ),
        migrations.AddField(
            model_name='day',
            name='start_location',
            field=models.TextField(default='Portland, OR'),
        ),
        migrations.AlterField(
            model_name='location',
            name='duration_hour',
            field=models.CharField(choices=[(None, 'H'), (1, '1 hour'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours'), (5, '5 hours'), (6, '6 hours'), (7, '7 hours'), (8, '8 hours'), (9, '9 hours'), (10, '10 hours'), (11, '11 hours'), (12, '12 hours')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='duration_min',
            field=models.CharField(choices=[(None, 'M'), (10, '10 minutes'), (20, '20 minutes'), (30, '30 minutes'), (40, '40 minutes'), (50, '50 minutes')], default=None, max_length=20),
        ),
    ]
