# Generated by Django 2.2.2 on 2019-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trversalapp', '0004_auto_20190624_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='mode',
            field=models.CharField(choices=[('DRIVING', 'Driving'), ('WALKING', 'Walking'), ('BICYCLING', 'Bicycling'), ('TRANSIT', 'Transit')], default='DRIVING', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='duration_hour',
            field=models.CharField(choices=[('0', 'H'), ('1', '1 hour'), ('2', '2 hours'), ('3', '3 hours'), ('4', '4 hours'), ('5', '5 hours'), ('6', '6 hours'), ('7', '7 hours'), ('8', '8 hours'), ('9', '9 hours'), ('10', '10 hours'), ('11', '11 hours'), ('12', '12 hours')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='duration_min',
            field=models.CharField(choices=[('00', 'M'), ('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes')], default='15', max_length=20),
        ),
    ]
